//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgisayar
    {
        public Bilgisayar()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int bilgisayar_id { get; set; }
        public string bilgisayar_marka { get; set; }
        public string bilgisayar_model { get; set; }
        public string bilgisayar_ram { get; set; }
        public Nullable<double> bilgisayar_boyut { get; set; }
        public string bilgisayar_hafiza { get; set; }
        public string bilgisayar_isletim_sistemi { get; set; }
        public string bilgisayar_ekrankarti_model { get; set; }
        public string bilgisayar_ekrankarti_boyut { get; set; }
        public string bilgisayar_garanti { get; set; }
        public string bilgisayar_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
