//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotograf_Makinesi
    {
        public Fotograf_Makinesi()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int fotoğraf_id { get; set; }
        public string fotoğraf_marka { get; set; }
        public string fotoğraf_model { get; set; }
        public string fotoğraf_cozunurluk { get; set; }
        public Nullable<double> fotoğraf_ekranboyutu { get; set; }
        public string fotoğraf_garanti { get; set; }
        public string fotoğraf_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
