//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_incelemeEntities : DbContext
    {
        public Db_incelemeEntities()
            : base("name=Db_incelemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilgisayar> Bilgisayars { get; set; }
        public virtual DbSet<Fotograf_Makinesi> Fotograf_Makinesi { get; set; }
        public virtual DbSet<Motorsiklet> Motorsiklets { get; set; }
        public virtual DbSet<Otomobil> Otomobils { get; set; }
        public virtual DbSet<Playstation> Playstations { get; set; }
        public virtual DbSet<Roller> Rollers { get; set; }
        public virtual DbSet<Sepet> Sepets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tablet> Tablets { get; set; }
        public virtual DbSet<Telefon> Telefons { get; set; }
        public virtual DbSet<Televizyon> Televizyons { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<Uyeler> Uyelers { get; set; }
        public virtual DbSet<Yorum> Yorums { get; set; }
    }
}
