//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorsiklet
    {
        public Motorsiklet()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int motorsiklet_id { get; set; }
        public string motorsiklet_marka { get; set; }
        public string motorsiklet_model { get; set; }
        public string motorsiklet_yil { get; set; }
        public string motorsiklet_km { get; set; }
        public string motorsiklet_motorgucu { get; set; }
        public string motorsiklet_silindir_sayisi { get; set; }
        public string motorsiklet_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
