//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otomobil
    {
        public Otomobil()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int otomobil_id { get; set; }
        public string otomobil_marka { get; set; }
        public string otomobil_model { get; set; }
        public string otomobil_yil { get; set; }
        public string otomobil_vites { get; set; }
        public string otomobil_km { get; set; }
        public string otomobil_kasatipi { get; set; }
        public string otomobil_renk { get; set; }
        public string otomobil_motorgucu { get; set; }
        public string otomobil_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
