//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playstation
    {
        public Playstation()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int playstation_id { get; set; }
        public string playstation_islemci { get; set; }
        public string playstation_model { get; set; }
        public string playstation_gpu { get; set; }
        public string playstation_hafiza { get; set; }
        public string playstation_garanti { get; set; }
        public string playstation_bluetooth { get; set; }
        public string playstation_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
