//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roller
    {
        public Roller()
        {
            this.Uyelers = new HashSet<Uyeler>();
        }
    
        public int rol_id { get; set; }
        public string rol_adi { get; set; }
    
        public virtual ICollection<Uyeler> Uyelers { get; set; }
    }
}
