//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablet
    {
        public Tablet()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int tablet_id { get; set; }
        public string tablet_marka { get; set; }
        public string tablet_model { get; set; }
        public string tablet_isletim_sistemi { get; set; }
        public string tablet_hafiza { get; set; }
        public string tablet_ekran_cozunurluk { get; set; }
        public string tablet_kamera { get; set; }
        public string tablet_bluetooth { get; set; }
        public string tablet_ram { get; set; }
        public string tablet_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
