//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefon
    {
        public Telefon()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int telefon_id { get; set; }
        public string telefon_marka { get; set; }
        public string telefon_model { get; set; }
        public string telefon_isletim_sistemi { get; set; }
        public string telefon_cozunurluk { get; set; }
        public string telefon_boyut { get; set; }
        public string telefon_arka_kamera { get; set; }
        public string telefon_on_kamera { get; set; }
        public string telefon_ram { get; set; }
        public string telefon_hafiza { get; set; }
        public string telefon_garanti { get; set; }
        public string telefon_resim { get; set; }
    
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
