//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public Urunler()
        {
            this.Sepets = new HashSet<Sepet>();
            this.Yorums = new HashSet<Yorum>();
        }
    
        public int urun_id { get; set; }
        public Nullable<int> otomobil_id { get; set; }
        public Nullable<int> telefon_id { get; set; }
        public Nullable<int> tablet_id { get; set; }
        public Nullable<int> tv_id { get; set; }
        public Nullable<int> bilgisayar_id { get; set; }
        public Nullable<int> playstation_id { get; set; }
        public Nullable<int> fotograf_makine_id { get; set; }
        public Nullable<int> motosiklet_id { get; set; }
    
        public virtual Bilgisayar Bilgisayar { get; set; }
        public virtual Fotograf_Makinesi Fotograf_Makinesi { get; set; }
        public virtual Motorsiklet Motorsiklet { get; set; }
        public virtual Otomobil Otomobil { get; set; }
        public virtual Playstation Playstation { get; set; }
        public virtual ICollection<Sepet> Sepets { get; set; }
        public virtual Tablet Tablet { get; set; }
        public virtual Telefon Telefon { get; set; }
        public virtual Televizyon Televizyon { get; set; }
        public virtual ICollection<Yorum> Yorums { get; set; }
    }
}
