//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public Uyeler()
        {
            this.Sepets = new HashSet<Sepet>();
            this.Yorums = new HashSet<Yorum>();
        }
    
        public int uye_id { get; set; }
        public string uye_adi { get; set; }
        public string uye_soyad { get; set; }
        public string uye_mail { get; set; }
        public string uye_sifre { get; set; }
        public Nullable<int> uye_tel { get; set; }
        public Nullable<int> rol_id { get; set; }
    
        public virtual Roller Roller { get; set; }
        public virtual ICollection<Sepet> Sepets { get; set; }
        public virtual ICollection<Yorum> Yorums { get; set; }
    }
}
